export { DATE_SPAN_TEMPLATE_VARIABLES as EVENT_SPAN_TEMPLATE_VARIABLES,
  DATE_SPAN_CONDITION_VARIABLES as EVENT_SPAN_CONDITION_VARIABLES,
  DATE_SPAN_TEMPLATE_TOKENS as EVENT_SPAN_TEMPLATE_TOKENS
} from '@wabs/plugin-sdk/date-template';
